### ISSUE TITLE
Watch Own Project

### ISSUE THREAD

**Issue by winny-** [philnguyen/json-type-provider#1]
I recently found this project, and am very excited to integrate it into my type racket code that does a nontrivial amount of json parsing!

I noticed @philnguyen is not watching their own project through GitHub's built-in notification system. (click Watch -> select Watching) 

I have interacted with other repositories where the repository owner/maintainer isn't subscribed to repository notifications, and noted that response times are often increased significantly (months to even years) because the repository maintainer has to look for the new issues and new pull requests.

As such I am opening this issue in the likelihood that this situation could happen to this very useful racket package.

Best,
winny-

**Comment by philnguyen** [comment]
Watched. Thanks!
